# Generated by Django 4.2.7 on 2023-11-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_break_table_alter_clockinclockout_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='timestamp_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='break',
            name='timestamp_start',
            field=models.DateTimeField(null=True),
        ),
    ]
